### ISSUE TITLE
Criar função para adicionar um  produto 

### ISSUE THREAD

**Issue by Tasg27** [nelsonbarbosa46/infood#146]

**Comment by nelsonbarbosa46** [comment]
Na função adicionar à BD os seguintes campos:
- nome
- preço
- quantidade disponível
- descrição
- imagem

**Comment by nelsonbarbosa46** [comment]
Obter o idMerchant antes de inserir na BD

**Comment by nelsonbarbosa46** [comment]
remover o ficheiro se nao conseguir inserir
