### ISSUE TITLE
Verificar se os campos nome,  preço e quantidade disponível ao adicionar um produto

### ISSUE THREAD

**Issue by Tasg27** [nelsonbarbosa46/infood#148]

**Comment by nelsonbarbosa46** [comment]
Antes de adicionar um produto, verificar se os campos estão vazios. Se algum deles estiverem vazios não adicionar à BD e retornar com erro.

**Comment by nelsonbarbosa46** [comment]
Antes de inserir verifica-se se o token não está vazio, se o id que está no token é igual ao do form, se o typeUser do token é igual ao 2, ver se os campos name, price e quantity não estão vazios, se o quantity é válido (inteiro) e maior que 0 e se o price é válido (número) e maior que 0.
