### ISSUE TITLE
Ao submeter o formulário de alterar imagem do produto, usar a função AJAX para alterar imagem na API

### ISSUE THREAD

**Issue by Tasg27** [nelsonbarbosa46/infood#155]

**Comment by nelsonbarbosa46** [comment]
A função AJAX tem de ser do tipo PUT e enviar a imagem (ou nulo se estiver vazio). Se for efetuado com sucesso aparecer uma mensagem a dizer que foi alterado com sucesso e se der erro mostrar que não foi alterado
